version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:1.33.0 # Ensure this is the latest stable tag from docs
    environment:
      BASEROW_PUBLIC_URL: 'https://baserow.sunderedechoes.com'
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:
